/* Homework 6
   Compile the code, gcdR.c, on a  Intel platform as follows:
                   gcc gcd.c -S -std=iso9899:1999

   Redo for Homework 7::
   Compare to the optimized code generated by 
                   gcc gcdR.c -O2 -S -std=iso9899:1999 
                   
   You can compare to the code generated by 
              gcc gcd.c -S -std=iso9899:1999   
   This was done for homework 1.         
*/



int gcdR(int a, int b) {
    if (a!=b) { 
      if (a > b) {
         return gcdR(a - b, b);
      } else {
         return gcdR(a, b-a);
      }
    } else {
      return a;
    }
}
     

